env:
  SUBFOLDER_NAME: packages/web

name: Deploy web client

on:
  push:
    branches:
      - master
    paths:
      - packages/web/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          sudo chmod 600 ~/.ssh/id_ed25519
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Change ssh key file permissions
        run: |
          chmod go-rwx ~/.ssh/id_ed25519
      - name: Remove git folder
        run: |
          rm -rf .git
      - name: Push
        working-directory: ${{ env.SUBFOLDER_NAME }}
        run: |
          git init
          git config user.email "github.deployer@gmail.com"
          git config user.name "Github Deployer"
          git remote add cloud git+ssh://git@push-par-clevercloud-customers.services.clever-cloud.com/app_bccc7bf3-9bbe-466b-b7e6-1011f.git
          git add .
          git commit -m "For deploy"
          git push -f -u cloud master
